version: "3.3"

services:
  bind:
    image: zimbra/zcs-bind:genesis
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    env_file: .env
    entrypoint:
      - /data/init
    hostname: bind

  zimbra:
    image: zimbra/zcs-foss:genesis
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    entrypoint:
      - /zimbra/init
    env_file: .env
    hostname: zimbra

  test:
    image: zimbra/zcs-foss-test
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - zimbra
    entrypoint:
      - /bin/sleep
      - infinity
    env_file: .env
    hostname: test

networks:
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.1.0/24
