version: "3.3"

services:
  test:
    image: zimbra/zcs-foss-test:multi-node
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    configs:
      - source: init_test
        target: /zimbra/init
        mode: 0777
      - source: init_common
        target: /zimbra/init-common
        mode: 0777
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - zimbra
      - mailbox
    entrypoint:
      - /zimbra/init
      - --shutdown
      - "no"
    env_file: .env
    hostname: test
    secrets:
      - dot-s3curl

  zimbra:
    image: localhost:5000/zcs-foss-base:latest
    configs:
      - source: init_common
        target: /zimbra/init-common
        mode: 0777
      - source: init_zimbra
        target: /zimbra/init
        mode: 0777
      - source: config_zimbra
        target: /zimbra/config.in
        mode: 0666
    env_file: .env
    entrypoint:
      - /zimbra/init
#    entrypoint:
#      - /bin/sleep
#      - infinity
    hostname: ${ZIMBRA_HOST_NAME}
    networks:
      - default
    ports:
      - "7071:7071"
      - "8143:143"
      - "8443:443"
      - "8993:993"

  mailbox:
    image: localhost:5000/zcs-foss-base:latest
    configs:
      - source: init_common
        target: /zimbra/init-common
        mode: 0777
      - source: init_mailbox
        target: /zimbra/init
        mode: 0777
      - source: config_mailbox
        target: /zimbra/config.in
        mode: 0666
    env_file: .env
    entrypoint:
      - /zimbra/init
#    entrypoint:
#      - /bin/sleep
#      - infinity
    hostname: ${MAILBOX_HOST_NAME}
    networks:
      - default

configs:
  init_common:
    file: ./zcs-foss/configs/init-common
  init_mailbox:
    file: ./zcs-foss/configs/init-mailbox
  config_mailbox:
    file: ./zcs-foss/configs/config-mailbox
  init_zimbra:
    file: ./zcs-foss/configs/init-zimbra
  config_zimbra:
    file: ./zcs-foss/configs/config-zimbra
  init_test:
    file: ./configs/init-test
networks:
  default:
    driver: overlay

secrets:
  dot-s3curl:
    external: true

