version: "3.3"

services:
  test:
    # image: localhost:5000/zcs-foss-test
    image: zimbra/zcs-foss-test:single-node
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - zimbra
    entrypoint:
      - /opt/qa/init
      - --shutdown
      - "no"
    env_file: .env
    hostname: test
    secrets:
      - dot-s3curl

networks:
  default:
    driver: overlay

secrets:
  dot-s3curl:
    external: true
