#!/bin/bash
# Perform runtime initialization of container. As part of that
# the file /opt/zimbra/qa/global.properties.in is used as a template
# from which the file /opt/zimbra/qa/global.properties is created.
#
# Expects the following envirnment variables to be present:
#   ZIMBRA_HOST_NAME
#   ZIMBRA_DEFAULT_DOMAIN
#   ADMIN_PW
#
# By default, the SanityTest suite will be run and the container will shut down.
# If, instead, additional argument(s) are provided to this script, then the initial
# configuration setup will still be performed, STAF will be started and the local
# services added, but instead of executing the SanityTest and exiting, the
# additional arguments will be executed.  For example, if this script is 
# called as follows (it will be installed in the container at /opt/qa/init)...
#
#   /opt/qa/init /bin/sleep inifinity
#
# ...then the container will be brought up and initialized, but won't do anything
# automatically.  You can then connect to the container (docker exec -it soap bash)
# and manually run individual tests.
# 

SLEEP_SECS=10
SLEEP_LONG_SECS=60
ZIMBRA_HOST_IP=$(getent hosts zimbra | awk '{print $1}')
while [ "${ZIMBRA_HOST_IP}x" = "x" ]; do
    echo "Waiting for zimbra container to start"
    sleep ${SLEEP_SECS}
    ZIMBRA_HOST_IP=$(getent hosts zimbra | awk '{print $1}')
done

# Add entry in /etc/hosts from ZIMBRA_HOST_NAME
# First check to make sure it hasn't already been appliec
grep -q "${ZIMBRA_HOST_NAME}" /etc/hosts
if [ $? != 0 ]; then
    echo "Adding mapping for ${ZIMBRA_HOST_NAME} to ${ZIMBRA_HOST_IP} in /etc/hosts"
    echo -e "${ZIMBRA_HOST_IP}\t${ZIMBRA_HOST_NAME}" >> /etc/hosts
else
    echo "An entry for ${ZIMBRA_HOST_NAME} is already present in /etc/hosts"
fi

# Update the config files
echo "updating soap-harness config"
cat /opt/qa/soapvalidator/conf/global.properties.in | sed \
  -e "s/ZIMBRA_HOST_NAME/${ZIMBRA_HOST_NAME}/" \
  -e "s/ZIMBRA_DEFAULT_DOMAIN/${ZIMBRA_DEFAULT_DOMAIN}/" \
  -e "s/ADMIN_PW/${ADMIN_PW}/" > /opt/qa/soapvalidator/conf/global.properties
cat /opt/qa/genesis/conf/genesis.conf.in | sed \
  -e "s/ZIMBRA_HOST_NAME/${ZIMBRA_HOST_NAME}/" \
  -e "s/ZIMBRA_DEFAULT_DOMAIN/${ZIMBRA_DEFAULT_DOMAIN}/" \
  -e "s/HOSTNAME/${HOSTNAME}/" > /opt/qa/genesis/conf/genesis.conf

# Fire up STAF
export PATH=/usr/local/staf/bin:$PATH
echo "starting STAF"
/usr/local/staf/startSTAFProc.sh
sleep ${SLEEP_SECS}
echo "adding STAF services"
STAF local service add service SOAP LIBRARY JSTAF EXECUTE /opt/qa/soapvalidator/bin/zimbrastaf.jar
STAF local service add service LOG LIBRARY STAFLog

# Wait for the Zimbra container to finish configuration
curl -s -k https://${ZIMBRA_HOST_NAME} > /dev/null
while [ $? -ne 0 ]; do
    echo "Waiting for ${ZIMBRA_HOST_NAME} services to come up.  Sleeping for ${SLEEP_LONG_SECS} seconds..."
    sleep ${SLEEP_LONG_SECS}
    curl -s -k https://${ZIMBRA_HOST_NAME} > /dev/null
done

if [ $# -eq 0 ]
then
    echo "running SanityTest suite"
    STAF LOCAL soap EXECUTE ${ZIMBRA_HOST_NAME} ZIMBRAQAROOT /opt/qa/soapvalidator/ DIRECTORY  /opt/qa/soapvalidator/data/soapvalidator/SanityTest/ LOG /opt/qa/results/soap-harness  SUITE SANITY
    /bin/sleep/inifinity
else
    echo "running ${@}"
    $@
fi
